

// Sides:	A => Api
//			C => Client
//			R => Regietool
//
export enum socketMessageTypes {
	// Info
	AC_HELLO,

	// Ping, Pong!
	AC_PING,	// See: XX_PING
	CA_PONG,	// See: XX_PING

	// Auth
	AC_AUTHENTICATION_REQ,
	CA_AUTHENTICATION,
	AC_AUTHENTICATION_RESULT,
	AC_AUTHENTICATION_RENEW_TOKEN_REQ,

	// Notifications
	AC_NOTIFICATION,
	CA_NOTIFICATION_READ,
	CA_NOTIFICATION_DELETE,
	CA_NOTIFICATION_DELETE_ALL,
	AC_NOTIFICATION_READ,
	AC_NOTIFICATION_DELETE,
	AC_NOTIFICAITON_DELETE_ALL,

	//
	AC_STREAM_YOUTUBECHANGED,
	AC_STREAM_INFO,
	AC_STREAM_COUNT,


	// Episode Progress Related
	CA_MEDIA_EPISODEPROGRESS_UPDATE,

	// Interaction, Management; Regietool
	RA_INTERACTION_CREATE,
	AR_INTERACTION_CREATED,
	RA_INTERACTION_LIST_ACTIVE,
	AR_INTERACTION_LIST,
	RA_INTERACTION_ACTIVATE,
	RA_INTERACTION_DEACTIVATE,
	RA_INTERACTION_EVENT,
	RA_INTERACTION_EVENT2,	// uses socket-io native parameters for passing data between regietool && api
	AR_INTERACTION_EVENT,

	AC_DYNINTERACTION_START,
	AC_DYNINTERACTION_END,
	AC_DYNINTERACTION_EVENT,
	CA_DYNINTERACTION_EVENT,

	//
	AC_CONFETTI,
};
